### ISSUE TITLE
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'

### ISSUE THREAD

**Issue by XiaoZong0** [Elsaam2y/DINet_optimized#14]
when i  run inference with custom videos using conda, it always display this? what is the matter?

**Comment by Elsaam2y** [comment]
Sorry for the late response. This should be a problem with the codec. You need to make sure of the ffmpeg and codec installed, or try t convert the video to a format compatible with the XVID codec.

**Comment by Elsaam2y** [comment]
I would suggest you try building the docker container using the docker file I provided, and then run the test again.
