### ISSUE TITLE
为啥学习率降低50%都是302epoch，是不是哪里有问题？v

### ISSUE THREAD

**Issue by einsqing** [Elsaam2y/DINet_optimized#20]
为啥学习率降低50%都是302epoch，是不是哪里有问题？而且推理出来嘴巴惨不忍睹

**Comment by tailangjun** [comment]
> 为啥学习率降低50%都是302epoch，是不是哪里有问题？而且推理出来嘴巴惨不忍睹

老铁，你声学模型用的是wav2vec吗？

**Comment by tailangjun** [comment]
控制lr下降的是config中的两个参数 non_decay和 decay，默认都是200，在300时降低50%是符合预期的
