### ISSUE TITLE
New repo LipSick 

### ISSUE THREAD

**Issue by Inferencer** [Elsaam2y/DINet_optimized#24]
Ive created a new repo re-branding dinet into LipSick, I have upgraded it to python 3.10 added a few features such as removing the need for openface csv etc
I have tested this on windows linux collab & hugging face (including a free cpu version) so will be keeping it updated as the weeks go by, I have added you as a collaborator Elsaam2y if you feel like it.
While your repo is primarily speed focused mine is more feature rich focused on UX while retaining or improving quality  

https://github.com/Inferencer/LipSick

**Comment by Elsaam2y** [comment]
Thanks for the invitation :), this sounds very interesting.
