### ISSUE TITLE
How to get a video.csv file for a custom video in Conda ?

### ISSUE THREAD

**Issue by Neurophars** [Elsaam2y/DINet_optimized#9]

**Comment by davidmartinrius** [comment]
You mean you want to generate face landmarks with openface installed in conda? Openface without docker is a headache to install.

I don't know if you mean this because I need more details... What do you need exactly?

**Comment by Neurophars** [comment]
> Вы имеете в виду, что хотите создавать ориентиры на лицах с помощью openface, установленного в Конде? Openface без докера — головная боль при установке.
> 
> Я не знаю, имеете ли вы это в виду, потому что мне нужно больше подробностей... Что именно вам нужно?

Thanks for the quick reply, I already figured out how to make video.csv. Is it possible to make the mask like in my attached picture?
Or is the mask limited to a square?
![mask](https://github.com/Elsaam2y/DINet_optimized/assets/117477907/6e9e9dc2-3f31-48f6-bea1-02ad94b3ace6)

**Comment by davidmartinrius** [comment]
As far as I know this is limited to a square/rectangle. With Dinet implementation cheeks won't move.

**Comment by Neurophars** [comment]
> As far as I know this is limited to a square/rectangle. With Dinet implementation cheeks won't move.

Got it, thanks.

**Comment by Elsaam2y** [comment]
Feel free to reopen the issue if needed.
